{
 "title": "Dymension Validator",
 "description": "This Grafana dashboard provides a comprehensive and detailed view of the state and activity of nodes within the Dymension consensus system, allowing network administrators and developers to monitor various critical aspects of the infrastructure in real time. The interface is designed to facilitate the tracking of node synchronization performance and efficiency, as well as the participation and voting power of validators within the network. Through this panel, users can quickly identify potential issues or confirm the proper functioning of the system, ensuring optimal operation and network security for Dymension's blockchain. This resource is essential for maintaining transparency and effectiveness in upholding the integrity of the blockchain.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)\n" } }
  ]
 },
 "panels": [
  { "title": "Validator data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <img src=\"https://cumulo.pro/images/pic02.png\" alt=\"Logo\" style=\"height: 150px;\"> <!-- Ajusta la altura según sea necesario -->\n    <h2>Dymension validator metrics</h2>\n    <h5>by <a href=\"https://cumulo.pro\">Cumulo</a></h5>\n</div>"
   }
  },
  {
   "title": "Node Last Signed Height",
   "type": "stat",
   "description": "Last height the node signed a block, if the node is a validator",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_last_signed_height{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed blocks",
   "type": "stat",
   "description": "Number of missed blocks",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_missed_blocks{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Voting Power",
   "type": "stat",
   "description": "Voting power of the node if in the validator set",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_power{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Syncing",
   "type": "stat",
   "description": "indicates whether a node is synchronising its state",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_state_syncing{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "gauge",
   "description": "Number of peers node’s connected to",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "P2P Peers",
   "type": "timeseries",
   "description": "current number of peers in the network ",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{job=\"$job\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "SYNC STATUS",
   "type": "stat",
   "description": "Either NO SYNC (not block syncing) or SYNC (syncing)",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_fast_syncing{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consensus data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Consensus Height",
   "type": "stat",
   "description": "current height of the block in the Dymension consensus system",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº Transactions Committed",
   "type": "stat",
   "description": "number of transactions included in the block",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Validators Power",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators_power{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bonded tokens",
   "type": "stat",
   "description": "The total number of bonded tokens in the network",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Last Blocks Chain",
   "type": "timeseries",
   "description": "Status of the last blocks produced in the chain",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{job=\"$job\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "stat",
   "description": "Block size in bytes",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Total txs",
   "type": "stat",
   "description": "Total number of transactions processed in the Dymension consensus system since inception",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº Validators missing blocks",
   "type": "stat",
   "description": "Number of validators who did not sign in the Dymension consensus system",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Validators",
   "type": "gauge",
   "description": "Total number of active validators in the Celestia consensus",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Step Duration",
   "type": "timeseries",
   "description": "Histogram of durations for each step in the consensus protocol",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cometbft_consensus_step_duration_seconds_bucket{job=\"$job\"}",
     "legendFormat": "{{step}}"
    }
   ]
  },
  { "title": "Block data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Block Processing Time",
   "type": "timeseries",
   "description": "Time between BeginBlock and EndBlock in milliseconds in the Celestia system.",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(cometbft_state_block_processing_time_sum{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Processing Time"
    },
    {
     "expr": "increase(cometbft_consensus_block_interval_seconds_sum{job=\"$job\"}[$__rate_interval]) / 6",
     "legendFormat": "Interval"
    }
   ]
  },
  {
   "title": "Interval between Consensus Blocks",
   "type": "timeseries",
   "description": "Time elapsed between the current block and the previous block in the Celestia consensus system",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 37 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_bucket{job=\"$job\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Consensus Block Size Bytes",
   "type": "timeseries",
   "description": "Block size in bytes",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{job=\"$job\"}",
     "legendFormat": "Size Bytes"
    }
   ]
  },
  {
   "title": "Number of block parts received",
   "type": "stat",
   "description": "Number of block parts received by the node\n\nmatches_current=\"true\": Means that the received block part matches the block that the node is currently collecting. In other words, the received part is relevant to the block being formed.\n\nmatches_current=\"false\": Indicates that the received block part does not match the block that the node is currently collecting. This means that the received part is not relevant to the block the node is trying to form.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_gossip_parts_received{job=\"$job\"}",
     "legendFormat": "{{matches_current}}"
    }
   ]
  },
  {
   "title": "Block Interval Seconds Sum",
   "type": "timeseries",
   "description": "Time between this and the last block.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_sum{job=\"$job\"}",
     "legendFormat": "Seconds Sum"
    }
   ]
  },
  {
   "title": "Block Interval Seconds Count",
   "type": "timeseries",
   "description": "Total number of times a time interval between blocks has been observed in the Celestia system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_count{job=\"$job\"}",
     "legendFormat": "Seconds Count"
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Mempool size",
   "type": "timeseries",
   "description": "Number of transactions pending confirmation that have not yet been included in a block",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "cometbft_mempool_size{job=\"$job\"}",
     "legendFormat": "Number of transactions pending confirmation that have not yet been included in a block"
    }
   ]
  },
  {
   "title": "Mempool  tx Size Bytes",
   "type": "stat",
   "description": "Transaction sizes in bytes",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_tx_size_bytes_sum{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txs failed mempool",
   "type": "stat",
   "description": "number of transactions that have failed in the mempool (group of unconfirmed transactions).",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_failed_txs{job=\"$job\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Uncommitted transactions",
   "type": "stat",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool tx Size Bytes Sum",
   "type": "timeseries",
   "description": "The sum total of the size of all transactions in bytes present in the Celestia system mempool",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 61 },
   "targets": [
    {
     "expr": "cometbft_mempool_tx_size_bytes_sum{job=\"$job\"}",
     "legendFormat": " Transactions in bytes "
    }
   ]
  },
  { "title": "system monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Process CPU Seconds Total",
   "type": "gauge",
   "description": "total CPU time, both user and system, consumed by the process since its start-up",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Process Virtual Memory Usage",
   "type": "stat",
   "description": "Total amount of virtual memory used by the process in bytes",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Process Resident Memory Usage",
   "type": "stat",
   "description": "Sze of the resident memory used by the process, expressed in bytes",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration of Garbage Collection Pauses in Go",
   "type": "timeseries",
   "description": "This metric provides a summary of the duration of rubbish collection cycle pauses in the Go runtime environment.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 69 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{job=\"$job\"}",
     "legendFormat": "Seconds Sum"
    }
   ]
  }
 ]
}